name    'puppet-slurm'
version '0.0.0'
source 'https://github.com/seattle-biomed/puppet-slurm'
author 'Seattle Biomedical Research Institute'
license 'MIT'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'https://github.com/puppet/puppet-slurm'
